kind: Service
apiVersion: v1
metadata:
  name: "wai-demo"
spec:
  selector:
    app: "wai-demo"
    secure: "enabled"
  ports:
    - protocol: "TCP"
      port: 3100
      targetPort: 3000
      nodePort: 31000
  type: NodePort
