apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wai-scenario-2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wai-frontend
        track: stable
    spec:
      containers:
        - name: wai-demo
          image: "psibi/wai-sample-wai:latest"
